### ISSUE TITLE
selenium err due to metamask update

### ISSUE THREAD

**Issue by kasutu** [kurtatwork/KurtAtWork-OpenSea-Auto-Uploader#8]
### Hello, the Metamask website has been updated.

```
DevTools listening on ws://127.0.0.1:56295/devtools/browser/09034fd2-f012-447a-9b2c-0407fb61f4dc
Login to MetaMask extension. Logged to Metamask extension.
Login to Opensea. Traceback (most recent call last):
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 549, in <module>
    upload.opensea_login()
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 308, in opensea_login
    self.metamask_sign()
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 322, in metamask_sign
    self.element_clickable(
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 198, in element_clickable
    WDW(self.driver, 60).until(EC.element_to_be_clickable(
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=97.0.4692.71)
```

**Comment by PZYCO20** [comment]
edited.

**Comment by kurtatwork** [comment]
you need to update your chrome driver actually... its not metamask, its the chrome driver. google chrome updated their software.

The project comes with version 95... looks like 97 is needed now.
Download the new one and add it to the assets folder, removing the old one.

Let me know if that fixes it or not.

**Comment by kasutu** [comment]
![image](https://user-images.githubusercontent.com/64959978/149912151-b65e4770-83c6-4ae2-bdd6-7aa2f26d2abb.png)


hello sir, sad to say that the solution it didn't work. I already updated to chrome driver 97 and its stuck here in the opensea login page.

**Comment by mpi42** [comment]
same problem

**Comment by kurtatwork** [comment]
Ok, guys... thanks for the feedback, i'll be looking into this... Looks like either an update with chromebrowser or in metamask is throwing things off with the script. 

I'll be looking into this. 

For now, you should be able to download an older version of chrome (get 95), and perhaps try the script with that and the 95 version of chrome driver... If this doesn't fix it, then its def an issue with an update to metamask. (or OpenSea, they could have changed the xpath of the button)

I'll be working on this and researching... if anyone else wants to help look for a fix and contribute to the repo by adding to these open issues with additional info, it would be greatly appreciated. 

I'll be in touch.

**Comment by kasutu** [comment]
hello,

```
DevTools listening on ws://127.0.0.1:56235/devtools/browser/cf0d4a8e-9bcf-483f-a5d4-6993f72f8c86
Login to MetaMask extension. Logged to Metamask extension.
Login to Opensea. Traceback (most recent call last):
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 549, in <module>
    upload.opensea_login()
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 292, in opensea_login
    if self.element_visible(
  File "D:\Cloned From github\KurtAtWork-OpenSea-Auto-Uploader\main.py", line 208, in element_visible
    return WDW(self.driver, timer).until(EC.visibility_of_element_located(
  File "C:\Users\JEROME\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

Still got the error even i downgraded my google chrome and driver to 95, same situa tion stuck in the opensea `select wallet to login` page.

**Comment by kurtatwork** [comment]
Ah, ok... well, that narrows it down quite a bit... so it seems to be that OpenSea has made some changes to their site that has temporarily broken the script... I'll see about remedying this and make some commits. 

If anyone else wants to help troubleshoot the xpaths and make a pull request to the repo, it would be greatly appreciated.
Thanks everyone for your patience.

**Comment by omowanai** [comment]
any updates on this
? im having same issue
